repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

- repo: https://github.com/python-poetry/poetry
  rev: '1.4.0'
  hooks:
    - id: poetry-export
      args: ["-f", "requirements.txt", "--without-hashes", "-o", "requirements/prod.txt"]
      verbose: true
    - id: poetry-export
      args: ["--only", "dev", "-f", "requirements.txt", "--without-hashes", "-o", "requirements/dev.txt"]
      verbose: true

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
